name: gql_tools
description: GraphQL Code Generation Utility Tool
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  path: ^1.8.3

dev_dependencies:

